//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int AccessId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
